### ISSUE TITLE
Investigate issues with reporting on ESXi Host Datastore Specifications

### ISSUE THREAD

**Issue by tpcarman** [AsBuiltReport/AsBuiltReport.VMware.vSphere#17]
Report generation crashed with the following error when attempting to collect ESXi Host Datastore Specifications. 

`Cannot bind argument to parameter 'Rows' because it is an empty collection.`

Issue appears to be a missing `if` statement when collecting ESXi host datastore information. Currently code assumes all ESXi hosts will have a datastore. In this particular case, the report crashes when it tries to retrieve information from a vSAN witness.

**To Reproduce**
1. Attempt to generate a vSphere report where an ESXi host does not have any datastores configured.

**Expected behavior**
If a host does not have any datastores, the script should bypass collection

**Desktop (please complete the following information):**
 - Windows 10
 - PowerCLI 11.2
 - AsBuiltReport.VMware.vSphere 0.4.1

**Comment by tpcarman** [comment]
Resolved in https://github.com/AsBuiltReport/AsBuiltReport.VMware.vSphere/commit/f2d92ca468d781bc9464e0446fa9f4ead9973212

**Comment by akvirtualgeek** [comment]
I'm still seeing this as an issue... I used the new Invoke-AsBuiltReport.VMware.vSphere.ps1 file.... below is what I got.

VERBOSE: [ 10:13:12:420 ] [ Document ] - Processing paragraph 'The following section provides infor[..]'.
VERBOSE: [ 10:13:12:424 ] [ Document ] - Processing section 'M2-DSC00-MGMT02' started.
VERBOSE: [ 10:13:17:267 ] [ Document ] - Processing table 'M2-DSC00-MGMT02 vSAN Configuration'.
VERBOSE: [ 10:13:17:294 ] [ Document ] - Processing section 'M2-DSC00-MGMT02' completed.
VERBOSE: [ 10:13:17:298 ] [ Document ] - Processing section 'vSAN' completed.
VERBOSE: [ 10:13:17:348 ] [ Document ] - Processing section 'Datastores' started.
VERBOSE: [ 10:13:17:352 ] [ Document ] - Processing paragraph 'The following section provides infor[..]'.
VERBOSE: [ 10:13:17:354 ] [ Document ] - Processing section 'DE300180101439-01-01-service-datastore1' started.
VERBOSE: [ 10:13:17:417 ] [ Document ] - Processing table 'Datastore Specifications'.
VERBOSE: [ 10:13:17:434 ] [ Document ] - Processing section 'DE300180101439-01-01-service-datastore1' completed.
VERBOSE: [ 10:13:17:436 ] [ Document ] - Processing section 'DE300180101440-01-01-service-datastore1' started.
VERBOSE: [ 10:13:17:490 ] [ Document ] - Processing table 'Datastore Specifications'.
VERBOSE: [ 10:13:17:494 ] [ Document ] - Processing section 'DE300180101440-01-01-service-datastore1' completed.
VERBOSE: [ 10:13:17:496 ] [ Document ] - Processing section 'DE300180101441-01-01-service-datastore1' started.
VERBOSE: [ 10:13:17:531 ] [ Document ] - Processing table 'Datastore Specifications'.
VERBOSE: [ 10:13:17:537 ] [ Document ] - Processing section 'DE300180101441-01-01-service-datastore1' completed.
VERBOSE: [ 10:13:17:539 ] [ Document ] - Processing section 'DE300180101442-01-01-service-datastore1' started.
VERBOSE: [ 10:13:17:624 ] [ Document ] - Processing table 'Datastore Specifications'.
VERBOSE: [ 10:13:17:629 ] [ Document ] - Processing section 'DE300180101442-01-01-service-datastore1' completed.
VERBOSE: [ 10:13:17:630 ] [ Document ] - Processing section 'DE300180101444-01-01-service-datastore1' started.
VERBOSE: [ 10:13:17:680 ] [ Document ] - Processing table 'Datastore Specifications'.
VERBOSE: [ 10:13:17:685 ] [ Document ] - Processing section 'DE300180101444-01-01-service-datastore1' completed.
VERBOSE: [ 10:13:17:686 ] [ Document ] - Processing section 'VxRail-Virtual-SAN-Datastore-MGMT' started.
VERBOSE: [ 10:13:17:741 ] [ Document ] - Processing table 'Datastore Specifications'.
VERBOSE: [ 10:13:17:746 ] [ Document ] - Processing section 'VxRail-Virtual-SAN-Datastore-MGMT' completed.
VERBOSE: [ 10:13:17:748 ] [ Document ] - Processing section 'Datastores' completed.
VERBOSE: [ 10:13:17:810 ] [ Document ] - Processing section 'Datastore Clusters' started.
VERBOSE: [ 10:13:17:814 ] [ Document ] - Processing paragraph 'The following section provides infor[..]'.
VERBOSE: [ 10:13:17:818 ] [ Document ] - Processing section 'M2-VDP-MGMT' started.
VERBOSE: [ 10:13:17:825 ] [ Document ] - Processing paragraph 'The following table details the conf[..]'.
VERBOSE: [ 10:13:17:828 ] [ Document ] - Processing blank line.
New-AsBuiltReport : Attempted to divide by zero.
At line:1 char:1
+ New-AsBuiltReport -Report VMware.vSphere -Target m2-mgmt-vc01.gci.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by tpcarman** [comment]
Hi akvirtualgeek,
Are you able to provide more information with regards to datastore '
M2-VDP-MGMT'? What size is the datastore? Is it in maintenance mode or have
any unique specifications?
Thanks,
Tim

**Comment by tpcarman** [comment]
Reopening issue to investigate `Divide by zero` errors

**Comment by akvirtualgeek** [comment]
Sorry I deleted the comment online soon after I made it.

M2-VDP-MGMT It turns out was an empty data store cluster... once I deleted
it, the script completed successfully. This is probably a usecase that
wasn’t expected.

Jeremy Mayfield

**Comment by tpcarman** [comment]
Hi Jeremy,

I have just tested this in my homelab and it appears you have discovered a
bug. I will raise an issue for this.

Thanks for letting me know.

Cheers,
Tim.

**Comment by tpcarman** [comment]
Issue #35 opened to address the issue with the datastore cluster.
